const backup = [

{
    name : "Grail 8 Di2",
    maker : "Trek",
    image : "https://d2yn9m4p3q9iyv.cloudfront.net/trek/2023/procaliber-9.8/thumbs/400/d7de1.jpeg ",
    year : 2023, 
    category : "road",
    isEBike :false,
    gender : "girls",
    priceCurrency : "EUR",
    priceAmount : 4599, 
    softDelete : false,
}, 
{
    name : "Grail 72 ",
    maker : "",
    image : "https://d2yn9m4p3q9iyv.cloudfront.net/trek/2023/marlin-6-gen-3/thumbs/400/79ef5.jpeg",
    year : 2023, 
    category : "mountain",
    isEBike :false,
    gender : "boys",
    priceCurrency : "EUR",
    priceAmount : 4599, 
    softDelete : false,
}, 
{
    name : "Spectral 14",
    maker : "Trek",
    image : "https://d2yn9m4p3q9iyv.cloudfront.net/trek/2023/domane-al-4-disc/thumbs/400/f0a47.jpeg ",
    year : 2023, 
    category : "mountain",
    isEBike :false,
    gender : "girls",
    priceCurrency : "EUR",
    priceAmount : 4599, 
    softDelete : false,
}, 
{
    name : "Spectral 1223",
    maker : "",
    image : "https://d2yn9m4p3q9iyv.cloudfront.net/trek/2023/marlin-6-gen-2/thumbs/400/f1968.jpeg ",
    year : 2021, 
    category : "mountain",
    isEBike :false,
    gender : "boys",
    priceCurrency : "EUR",
    priceAmount : 4599, 
    softDelete : false,
}, 
{
    name : "Neuron 6 WMN 8",
    maker : "Canyon",
    image : "https://d2yn9m4p3q9iyv.cloudfront.net/trek/2023/domane-sl-6-gen-3/thumbs/400/5c386.jpeg ",
    year : 2023, 
    category : "mountain",
    isEBike :false,
    gender : "girls",
    priceCurrency : "USD",
    priceAmount : 3000, 
    softDelete : false,
}, 
{
    name : "Marlina 6 Gen",
    maker : "Trek",
    image : "https://d2yn9m4p3q9iyv.cloudfront.net/canyon/2023/speedmax-cfr-disc-di2/thumbs/400/b667e.jpeg ",
    year : 2023, 
    category : "road",
    isEBike :false,
    gender : "boys",
    priceCurrency : "EUR",
    priceAmount : 4300, 
    softDelete : false,
}, 
{
    name : "Showrun Split 1F",
    maker : "Canyon",
    image : "https://d2yn9m4p3q9iyv.cloudfront.net/trek/2023/domane-slr-9-gen-4/thumbs/400/1415a.jpeg ",
    year : 2023, 
    category : "mountain",
    isEBike :false,
    gender : "girls",
    priceCurrency : "EUR",
    priceAmount : 4399, 
    softDelete : false,
}, 
{
    name : "Cast Shower 12",
    maker : "",
    image : "https://d2yn9m4p3q9iyv.cloudfront.net/specialized/2023/sirrus-2.0-step-through-eq/thumbs/400/cfcf1.jpeg ",
    year : 2023, 
    category : "mountain",
    isEBike :false,
    gender : "boys",
    priceCurrency : "EUR",
    priceAmount : 3999, 
    softDelete : false,
}, 
{
    name : "Pro Mountain 28",
    maker : "Trek",
    image : "https://d2yn9m4p3q9iyv.cloudfront.net/trek/2023/domane-al-3-disc/thumbs/400/be96b.jpeg ",
    year : 2023, 
    category : "mountain",
    isEBike :false,
    gender : "girls",
    priceCurrency : "EUR",
    priceAmount : 4999, 
    softDelete : false,
}, 
{
    name : "Spectral 28",
    maker : "Specialized",
    image : "https://d2yn9m4p3q9iyv.cloudfront.net/canyon/2023/speedmax-cf-slx-8-disc-di2/thumbs/400/11238.jpeg ",
    year : 2023, 
    category : "mountain",
    isEBike :false,
    gender : "boys",
    priceCurrency : "EUR",
    priceAmount : 3799, 
    softDelete : false,
}, 
{
    name : "Scarmitur 32 ADS 12",
    maker : "Marin",
    image : "https://d2yn9m4p3q9iyv.cloudfront.net/specialized/2023/s-works-tarmac-sl7-shimano-dura-ace-di2/thumbs/400/8ae70.jpeg ",
    year : 2023, 
    category : "road",
    isEBike :false,
    gender : "girls",
    priceCurrency : "EUR",
    priceAmount : 3299, 
    softDelete : false,
}, 
{
    name : "Crimbel 22.4 NJ 3",
    maker : "Marin",
    image : "https://d2yn9m4p3q9iyv.cloudfront.net/orbea/2023/rise-h20-20mph/thumbs/400/8b12a.jpeg ",
    year : 2023, 
    category : "mountain",
    isEBike :false,
    gender : "boys",
    priceCurrency : "EUR",
    priceAmount : 3899, 
    softDelete : false,
}, 
{
    name : "Monster 25 CF 8",
    maker : "Marin",
    image : "https://d2yn9m4p3q9iyv.cloudfront.net/trek/2023/checkpoint-alr-5-driftless/thumbs/400/9ed72.jpeg",
    year : 2023, 
    category : "mountain",
    isEBike :false,
    gender : "girls",
    priceCurrency : "EUR",
    priceAmount : 4199, 
    softDelete : false,
}, 
{
    name : "Magical",
    maker : "Specialized",
    image : "https://d2yn9m4p3q9iyv.cloudfront.net/orbea/2023/rise-h30-20mph/thumbs/400/47f45.jpeg ",
    year : 2023, 
    category : "mountain",
    isEBike :false,
    gender : "boys",
    priceCurrency : "EUR",
    priceAmount : 4299, 
    softDelete : false,
}, 
{
    name : "Spectricum CF 8",
    maker : "Marin",
    image : "https://d2yn9m4p3q9iyv.cloudfront.net/orbea/2023/rise-h20-20mph/thumbs/400/8b12a.jpeg ",
    year : 2023, 
    category : "road",
    isEBike :false,
    gender : "girls",
    priceCurrency : "EUR",
    priceAmount : 3599, 
    softDelete : false,
}, 
{
    name : "Climberst",
    maker : "Marin",
    image : "https://d2yn9m4p3q9iyv.cloudfront.net/orbea/2023/rise-m10-20mph/thumbs/400/b5f59.jpeg ",
    year : 2023, 
    category : "road",
    isEBike :false,
    gender : "boys",
    priceCurrency : "EUR",
    priceAmount : 3199, 
    softDelete : false,
}, 


]

module.exports = backup